name: download

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  download-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.8'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: download 
        run: python bin/download.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "napo"
          git config user.email "napo@fbk.eu"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
